### ISSUE TITLE
plotting beam phase space from Elegant window does not work

### ISSUE THREAD

**Issue by andonian** [radiasoft/radtrack#144]
Traceback (most recent call last):
  File "/home/vagrant/src/radiasoft/radtrack/radtrack/RbGlobal.py", line 130, in <lambda>
    self.ui.actionImport_File.triggered.connect(lambda : self.importFile())
  File "/home/vagrant/src/radiasoft/radtrack/radtrack/RbGlobal.py", line 307, in importFile
    self.tabWidget.currentWidget().importFile(openFile)
  File "/home/vagrant/src/radiasoft/radtrack/radtrack/rbdcp.py", line 128, in importFile
    self.showDCP_ele(openFile)
  File "/home/vagrant/src/radiasoft/radtrack/radtrack/rbdcp.py", line 219, in showDCP_ele
    self.fileData.load(openFile)
  File "/home/vagrant/.pyenv/versions/src/lib/python2.7/site-packages/sdds.py", line 96, in load
    self.columnData[i].append(sddsdata.GetColumn(self.index,i))
SystemError: error return without exception set

**Comment by MZHarrison** [comment]
Do you have a file that caused this error or can you list the actions you took that led to this?
