### ISSUE TITLE
viewing output from genesis tab broken

### ISSUE THREAD

**Issue by qedseung** [radiasoft/radtrack#156]
I think something from simulationResultTools is trying to perform ascii operations on unicode? Thus can no longer export to data viz.

/home/vagrant/src/radiasoft/radtrack/radtrack/util/stringTools.py:42: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if line[i] == commentCharacter and not insideQuote(line, i) and not characterEscaped(line, i):
Traceback (most recent call last):
  File "/home/vagrant/src/radiasoft/radtrack/radtrack/genesis_controller.py", line 45, in <lambda>
    position))
  File "/home/vagrant/src/radiasoft/radtrack/radtrack/util/simulationResultsTools.py", line 45, in results_context_menu
    if can_accept(tabType, file_name):
  File "/home/vagrant/src/radiasoft/radtrack/radtrack/util/simulationResultsTools.py", line 35, in can_accept
    if is_file_type(file_name, file_type):
  File "/home/vagrant/src/radiasoft/radtrack/radtrack/util/simulationResultsTools.py", line 28, in is_file_type
    elegantFileImport(file_name)
  File "/home/vagrant/src/radiasoft/radtrack/radtrack/beamlines/RbElegantElements.py", line 1182, in <lambda>
    fileImporter = lambda fileName : importFile(fileName, None, classDictionary, nameMangler)
  File "/home/vagrant/src/radiasoft/radtrack/radtrack/beamlines/RbElegantElements.py", line 34, in importFile
    line = ''.join([previousLine, line]).strip()
UnicodeDecodeError: 'ascii' codec can't decode byte 0x89 in position 0: ordinal not in range(128)
Traceback (most recent call last):
  File "/home/vagrant/src/radiasoft/radtrack/radtrack/genesis_controller.py", line 45, in <lambda>
    position))
  File "/home/vagrant/src/radiasoft/radtrack/radtrack/util/simulationResultsTools.py", line 45, in results_context_menu
    if can_accept(tabType, file_name):
  File "/home/vagrant/src/radiasoft/radtrack/radtrack/util/simulationResultsTools.py", line 35, in can_accept
    if is_file_type(file_name, file_type):
  File "/home/vagrant/src/radiasoft/radtrack/radtrack/util/simulationResultsTools.py", line 28, in is_file_type
    elegantFileImport(file_name)
  File "/home/vagrant/src/radiasoft/radtrack/radtrack/beamlines/RbElegantElements.py", line 1182, in <lambda>
    fileImporter = lambda fileName : importFile(fileName, None, classDictionary, nameMangler)
  File "/home/vagrant/src/radiasoft/radtrack/radtrack/beamlines/RbElegantElements.py", line 34, in importFile
    line = ''.join([previousLine, line]).strip()
UnicodeDecodeError: 'ascii' codec can't decode byte 0x89 in position 0: ordinal not in range(128)
Traceback (most recent call last):
  File "/home/vagrant/src/radiasoft/radtrack/radtrack/genesis_controller.py", line 45, in <lambda>
    position))
  File "/home/vagrant/src/radiasoft/radtrack/radtrack/util/simulationResultsTools.py", line 45, in results_context_menu
    if can_accept(tabType, file_name):
  File "/home/vagrant/src/radiasoft/radtrack/radtrack/util/simulationResultsTools.py", line 35, in can_accept
    if is_file_type(file_name, file_type):
  File "/home/vagrant/src/radiasoft/radtrack/radtrack/util/simulationResultsTools.py", line 28, in is_file_type
    elegantFileImport(file_name)
  File "/home/vagrant/src/radiasoft/radtrack/radtrack/beamlines/RbElegantElements.py", line 1182, in <lambda>
    fileImporter = lambda fileName : importFile(fileName, None, classDictionary, nameMangler)
  File "/home/vagrant/src/radiasoft/radtrack/radtrack/beamlines/RbElegantElements.py", line 34, in importFile
    line = ''.join([previousLine, line]).strip()
UnicodeDecodeError: 'ascii' codec can't decode byte 0x89 in position 0: ordinal not in range(128)

**Comment by MarkZH** [comment]
How did this error come about? Can you attach a file or list steps that cause this problem?

**Comment by qedseung** [comment]
hit simulate on the genesis tab and right click on lcls.out.h5

**Comment by MZHarrison** [comment]
Fixed by commit 1d14f49f279e89dc36dc84681ef62dac427a49ff. A warning is still printed to the command line, but the behavior in the GUI is now correct.
