### ISSUE TITLE
recent project examples reload 

### ISSUE THREAD

**Issue by qedseung** [radiasoft/radtrack#158]
reloading the fodo example via file>recent projects>Example_etc... error dialog incessantly: "beamline source contains no beamline" 

A blank error dialog also pops up with it after clicking ok.

**Comment by qedseung** [comment]
for got to include the trace:
[2.7.10;@rsdev radiasoft]$ radtrack
libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
Traceback (most recent call last):
  File "/home/vagrant/src/radiasoft/radtrack/radtrack/genesis_controller.py", line 178, in <lambda>
    i.clicked.connect(lambda:self.from_tab('beam',pu))
  File "/home/vagrant/src/radiasoft/radtrack/radtrack/genesis_controller.py", line 278, in from_tab
    print(self._view.parent.parent.tabWidget.widget(selected[0]).ui.simulationResultsListWidget.item[i].text())
TypeError: 'builtin_function_or_method' object has no attribute '__getitem__'
[2.7.10;@rsdev radiasoft]$ radtrack
libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
Traceback (most recent call last):
  File "/home/vagrant/src/radiasoft/radtrack/radtrack/RbGlobal.py", line 540, in checkMenus
    widget.update_sources_from_tabs()
  File "/home/vagrant/src/radiasoft/radtrack/radtrack/RbEle.py", line 182, in update_sources_from_tabs
    self.beam_line_source_manager._beam_line_source_changed()
  File "/home/vagrant/src/radiasoft/radtrack/radtrack/RbEle.py", line 837, in _beam_line_source_changed
    self._validate_and_load_beam_lines(loader)
  File "/home/vagrant/src/radiasoft/radtrack/radtrack/RbEle.py", line 855, in _validate_and_load_beam_lines
    del self.loaderCache[fileName]
KeyError: u''
lcls.lat
lcls.out
lcls.dist
Traceback (most recent call last):
  File "/home/vagrant/src/radiasoft/radtrack/radtrack/RbGlobal.py", line 540, in checkMenus
    widget.update_sources_from_tabs()
  File "/home/vagrant/src/radiasoft/radtrack/radtrack/RbEle.py", line 182, in update_sources_from_tabs
    self.beam_line_source_manager._beam_line_source_changed()
  File "/home/vagrant/src/radiasoft/radtrack/radtrack/RbEle.py", line 837, in _beam_line_source_changed
    self._validate_and_load_beam_lines(loader)
  File "/home/vagrant/src/radiasoft/radtrack/radtrack/RbEle.py", line 855, in _validate_and_load_beam_lines
    del self.loaderCache[fileName]
KeyError: u''
Traceback (most recent call last):
  File "/home/vagrant/src/radiasoft/radtrack/radtrack/RbEle.py", line 383, in _process_started
    self.beamlineNames = beamline_source.elementDictionary[beamlineName].fullElementNameList()
KeyError: u'FODO_BEAMLINE_X10'
Traceback (most recent call last):
  File "/home/vagrant/src/radiasoft/radtrack/radtrack/RbEle.py", line 383, in _process_started
    self.beamlineNames = beamline_source.elementDictionary[beamlineName].fullElementNameList()
KeyError: u'FODO_BEAMLINE_X10'
Traceback (most recent call last):
  File "/home/vagrant/src/radiasoft/radtrack/radtrack/RbEle.py", line 837, in _beam_line_source_changed
    self._validate_and_load_beam_lines(loader)
  File "/home/vagrant/src/radiasoft/radtrack/radtrack/RbEle.py", line 855, in _validate_and_load_beam_lines
    del self.loaderCache[fileName]
KeyError: u''
Traceback (most recent call last):
  File "/home/vagrant/src/radiasoft/radtrack/radtrack/RbGlobal.py", line 540, in checkMenus
    widget.update_sources_from_tabs()
  File "/home/vagrant/src/radiasoft/radtrack/radtrack/RbEle.py", line 182, in update_sources_from_tabs
    self.beam_line_source_manager._beam_line_source_changed()
  File "/home/vagrant/src/radiasoft/radtrack/radtrack/RbEle.py", line 837, in _beam_line_source_changed
    self._validate_and_load_beam_lines(loader)
  File "/home/vagrant/src/radiasoft/radtrack/radtrack/RbEle.py", line 855, in _validate_and_load_beam_lines
    del self.loaderCache[fileName]
KeyError: u''
Traceback (most recent call last):
  File "/home/vagrant/src/radiasoft/radtrack/radtrack/RbGlobal.py", line 540, in checkMenus
    widget.update_sources_from_tabs()
  File "/home/vagrant/src/radiasoft/radtrack/radtrack/RbEle.py", line 182, in update_sources_from_tabs
    self.beam_line_source_manager._beam_line_source_changed()
  File "/home/vagrant/src/radiasoft/radtrack/radtrack/RbEle.py", line 837, in _beam_line_source_changed
    self._validate_and_load_beam_lines(loader)
  File "/home/vagrant/src/radiasoft/radtrack/radtrack/RbEle.py", line 855, in _validate_and_load_beam_lines
    del self.loaderCache[fileName]
KeyError: u''
Traceback (most recent call last):
  File "/home/vagrant/src/radiasoft/radtrack/radtrack/RbGlobal.py", line 540, in checkMenus
    widget.update_sources_from_tabs()
  File "/home/vagrant/src/radiasoft/radtrack/radtrack/RbEle.py", line 182, in update_sources_from_tabs
    self.beam_line_source_manager._beam_line_source_changed()
  File "/home/vagrant/src/radiasoft/radtrack/radtrack/RbEle.py", line 837, in _beam_line_source_changed
    self._validate_and_load_beam_lines(loader)
  File "/home/vagrant/src/radiasoft/radtrack/radtrack/RbEle.py", line 855, in _validate_and_load_beam_lines
    del self.loaderCache[fileName]
KeyError: u''
Traceback (most recent call last):
  File "/home/vagrant/src/radiasoft/radtrack/radtrack/RbGlobal.py", line 540, in checkMenus
    widget.update_sources_from_tabs()
  File "/home/vagrant/src/radiasoft/radtrack/radtrack/RbEle.py", line 182, in update_sources_from_tabs
    self.beam_line_source_manager._beam_line_source_changed()
  File "/home/vagrant/src/radiasoft/radtrack/radtrack/RbEle.py", line 837, in _beam_line_source_changed
    self._validate_and_load_beam_lines(loader)
  File "/home/vagrant/src/radiasoft/radtrack/radtrack/RbEle.py", line 855, in _validate_and_load_beam_lines
    del self.loaderCache[fileName]
KeyError: u''
Traceback (most recent call last):
  File "/home/vagrant/src/radiasoft/radtrack/radtrack/RbGlobal.py", line 540, in checkMenus
    widget.update_sources_from_tabs()
  File "/home/vagrant/src/radiasoft/radtrack/radtrack/RbEle.py", line 182, in update_sources_from_tabs
    self.beam_line_source_manager._beam_line_source_changed()
  File "/home/vagrant/src/radiasoft/radtrack/radtrack/RbEle.py", line 837, in _beam_line_source_changed
    self._validate_and_load_beam_lines(loader)
  File "/home/vagrant/src/radiasoft/radtrack/radtrack/RbEle.py", line 855, in _validate_and_load_beam_lines
    del self.loaderCache[fileName]
KeyError: u''
lcls.lat
lcls.out
lcls.dist
Traceback (most recent call last):
  File "/home/vagrant/src/radiasoft/radtrack/radtrack/RbGlobal.py", line 540, in checkMenus
    widget.update_sources_from_tabs()
  File "/home/vagrant/src/radiasoft/radtrack/radtrack/RbEle.py", line 182, in update_sources_from_tabs
    self.beam_line_source_manager._beam_line_source_changed()
  File "/home/vagrant/src/radiasoft/radtrack/radtrack/RbEle.py", line 837, in _beam_line_source_changed
    self._validate_and_load_beam_lines(loader)
  File "/home/vagrant/src/radiasoft/radtrack/radtrack/RbEle.py", line 855, in _validate_and_load_beam_lines
    del self.loaderCache[fileName]
KeyError: u''

**Comment by qedseung** [comment]
![screen shot 2016-06-15 at 12 08 25 pm](https://cloud.githubusercontent.com/assets/10424478/16093857/7fb73d7e-32f2-11e6-8b0a-25dbcbee9070.png)
